- probe_printer.py
This means it shows up first (and is selected) during the scan.
Fixes #9.
> PrinterFinder: run hplip probe first (#9)

- ui/PrintersWindow.ui
There is no point in making this property translatable. In fact, there
is no point in having this property at all, because the title of the
window is reset when the program starts.
> Remove PrintersWindow title

- cupshelpers/openprinting.py
Do this to try to query for the right driver from Openprinting, regardless
of the kernel and user-space not matching the effective architecture, falling
back to Python's platform.machine() in case of error.
https://phabricator.endlessm.com/T10803
> openprinting: Use 'i386' as architecture when running in 32bit mode

- po/de.po
The capitalisation is wrong. Also, is it correct that this button has no accessor-key?
> Fixed wrong capitalization (German/de)

- system-config-printer.py
This PR includes a patch for offering an embedded mode for system-config-printer. This is used in Mageia for integrating system-config-printer with the Mageia Control Center. It was originally written by Tiago Salem of Mandriva for replacing PrinterDrake in the Mandriva Control Center for Mandriva 2009, and has been maintained in Mageia for successive versions of system-config-printer.
> Offer an embedded mode for system-config-printer

- ui/ConnectDialog.ui
By allowing the text entry child of the dialog's combobox to get focus
the user can edit it. This fixes the problem that currently the user
can't write anything in the combobox, so there's no way for someone
to write (for example) the ip where the CUPS server is.
> Make the combobox text entry child focusable

- NEWS
- system-config-printer.py
Hi ! 
I noticed that the `Start Service` button didn't work on my ArchLinux system, because I was using **systemd**.  I adapted the program to try launching `org.cups.cupsd.service` through systemd if the system is detected to use systemd (i.e. `/usr/lib/systemd` exists), and use **SysV** otherwise (the current default).
The fix did the job on my machine and the edits are pretty straightforward.  Feel free to ask if something is not clear enough.
> Add a StartService for systemd based systems

- ui/PrinterPropertiesDialog.ui
The action area of the printer properties dialog is expanded vertically when the dialog is resized.
Tested under Debian Stretch with available dialog screenshots in minor bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858575
> Adds printer properties dialog vertical expansion

- statereason.py
- ui/InstallDialog.ui
- ui/NewPrinterWindow.ui
- ui/PrinterPropertiesDialog.ui
- ui/WaitWindow.ui
GTK 3.0 has depreated or rename a bunch of icons, follow the new naming
conventions
See: https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
> Replace icons deprecated by GTK 3.0 by non-deprecated ones

- PhysicalDevice.py
- cupshelpers/cupshelpers.py
- cupshelpers/ppds.py
- installpackage.py
- newprinter.py
- options.py
- printerproperties.py
- system-config-printer.py
- ui/NewPrinterWindow.ui
- xml/preferreddrivers.xml
This is the collection of improvements an fixes which I have done on system-config-printer during the last few months as part of the Ubuntu packaging.
These are all small independent patches which should all be interesting for upstream, but they also should work if only a part gets adopted.
Here is an overview of the changes:
- Display correct icons in the main window.
Fixed display of printer icons in the main window, now the icons correctly represent local printers and network prrinters taking into account all recent changes in CUPS and cups-filters.
- Prefer driverless PPDs if suitable
Prioritize auto-generated PPD files for driverless printing, as they poll the properties from the printer, and so they represent the printer best.
- Do not use driverless PPDs on non-IPP connections
Make …
> Changes from Ubuntu: Driverless printing support, silence console, minor fixes

- PhysicalDevice.py
- cupshelpers/cupshelpers.py
- newprinter.py
Let entries for USB printing appear before USB fax entries in the connection type list
On a USB multi-function device the printing functionality is much more important than the fax functionality. Most users only use the printing part, and the fax part is also often not supported by an appropriate driver. So let the entry for printing appear first in the connection type list.
When listing discovered USB devices, distinguish between printer and fax
Some USB printers appear as two USB devices, one for printing and one for fax. This would lead to 2 connection types in the connection type list which are names "USB" and undistinguishable. Now we check on USB printer entries whether they are for fax and mark them as "Fax - USB".
Consider entries for HP printers as the same physical device if the …
> Improvements of discovered devices/conection type lists in new-printer wizard, more debug output

- print-applet.desktop.in
{gnome,cinnamon}-settings-daemon are also claiming the D-Bus interfaces
provided by the applet
> Do not start the applet on GNOME and Cinnamon desktops (Closes: #40)

- Makefile.am
`/usr/share/metainfo/` has been the [preferred location](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location) for appstream metadata since appstream 0.9.4 a year and a half ago
> build: Install appstream metadata to non-deprecated location

- authconn.py
47973c80 (Remove deprecated Gtk objects) broke the auth dialog.
Fixes https://bugs.archlinux.org/task/57364.
> Fix constructing the auth dialog

- scp-dbus-service.py
Please find here 2 fixes for scp-dbus-service
As scp-dbus-service can be D-Bus activated, these parts of the code from system-config-printer.py are never called. We should explicitly call them there
> Several fixes for scp-dbus-service

- scp-dbus-service.py
On openSUSE, LC_MESSAGES is not set by default, so fallback to LC_CTYPE in
that case.
Also, self._language is not a list (unlike in other classes) but the language
itself, so if we get the first element, we would be getting the first letter,
not the language.
> Fallback to using LC_CTYPE if LC_MESSAGES is empty and fix _language use

- options.py
- this error is caused by typo in options.py:424 debugprint call
- debugprint function takes only one parameter so i think it should
have been formated string
- fix https://bugzilla.redhat.com/show_bug.cgi?id=1619593
> Fix TypeError raised by debugprint call

- dbus/com.redhat.NewPrinterNotification.conf
- dbus/com.redhat.PrinterDriversInstaller.conf
As described in [0], this likely did not have the intended effect, so
simply remove it. The change in behavior is that up until this patch
it would be possible for root and any non-system user to potentially
own the system-config-printer dbus names. Now this is extended to also
allow any system user.
[0]: <https://www.spinics.net/lists/linux-bluetooth/msg75267.html>
Signed-off-by: Tom Gundersen <teg@jklm.no>
CC: David Herrmann <dh.herrmann@gmail.com>
> dbus: remove deprecated at_console statement

- authconn.py
- cupspk.py
- troubleshoot/DeviceListed.py
- troubleshoot/ErrorLogCheckpoint.py
- troubleshoot/ErrorLogFetch.py
- troubleshoot/__init__.py
- allow timestamp to be accessible through whole
troubleshoot process
- fix dbus call to get devices from cups
- if dbus method call has empty array as an argument then it needs
to have explicitly set signature
- fix some errors with temporary files
- fix rhbz1577082
> Fix troubleshoot

- cupspk.py
- serversettings.py
Hi,
These commits Fix #37 
For more information please see commit messages.
> Fix problems with saving of advanced settings

- scp-dbus-service.py
9ae2308a8e02527b34f6216162c88ebae04d8dc4 removed many of these but these two were left over.
@pwithnall noticed this when I was backporting that patch to Endless OS. I have not actually tested this change.
> Remove more uses of deprecated GObject.SIGNAL_RUN_LAST

- NEWS
- system-config-printer.appdata.xml.in
- ui/AboutDialog.ui
I removed non functional links from the project. They became non functional after moving to OpenPrinting.
> Removing zdohnal from links

- troubleshoot/base.py
Fix translation in troubleshoot menu.
Replaced the function '_' with the correct one.
=> The correct domain name is being loaded ('system-config-printer').
> fix translation in troubleshoot menu

- jobviewer.py
Right now, while saving the password to the keyring works perfectly (when "Remember Password" is picked), loading from the keyring fails.
There's 2 issues at hand here:
- `gi.Secret.Service` doesn't work async on python for some reason. The _final never fires. I could replicate this issue on a variety of distributions. So to fix this, I moved those functions to the relevant sync methods. While this isn't ideal, it fixes the bug at hand. `gi.Secret.PasswordStore` does seem to work.
- The .secret and .attribute functions of Secret.Item objects give out `gi.overrides.Gio._DBusProxyMethodCall` objects, not the actual contents. I ended up using `.get_secret().get()` (returns `bytes`) and `.get_attributes()["user"]` (returns `str`). I feel like the change on user especially was important, as …
> Fix "remember password" feature

- udev/70-printers.rules
- udev/udev-configure-printer.c
* Update the udev rule due to usb_id udev import is disabled in some systems.
* Make the matching rule of printer device path more flexible.
> Make the matching rule of printer device path more flexible

- asyncpk1.py
This reverts aa6500531326c4895f70f238a75f4537fe3532db
Properly fix #179
> asyncpk1.py: Import the gi module before calling gi.require_version

- Makefile.am
- configure.ac
Useful when building for embedded systems that don't use manuals.
> Add option to disable xmlto manual generation.

- README.md
- cupshelpers/openprinting.py
- newprinter.py
At this stage, this is mostly just a request for comments. I'm trying to remove python3-requests as a dependency of the Ubuntu base system. This project has been mostly successful for the server edition, since these patches made it possible to run Ubuntu 21.04 and later without python3-requests:
* https://code.launchpad.net/~slingamn/ssh-import-id/+git/ssh-import-id/+merge/389139
* https://bugs.launchpad.net/ubuntu/+source/apport/+bug/1903605
* https://code.launchpad.net/~ddstreet/software-properties/+git/software-properties/+merge/396926
For 22.04 I'd like to remove it as a dependency of the desktop system as well. I think system-config-printer is the only "core" package that still depends on it, so here's a draft of a patch that removes the dependency.
I wasn't sure how best to test …
> remove python3-requests

- serversettings.py
In the manual of cupsd.conf, the default setting of PerserveJobFiles is '86400';
but in serversettings.py, the default setting of preserve_job_files is 'False'.
> fix preserve_job_files default settings

- system-config-printer.py
Adds an optional dependency on libhandy >= 1.5
Here's a [developer blog post](https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/) about the feature.
> Support GNOME 42 dark style preference

- system-config-printer.py
- ui/NewPrinterWindow.ui
- ui/PrinterPropertiesDialog.ui
Greetings everybody,  
I’ve been working on making this program fully usable by visually-impaired users;  
this is what I’m coming up with so far; a big stumbling block remains the troubleshooter,  
but I’m hoping to offer a fix in the future about that.
> Accessibility improvements

- .github/dependabot.yml
- .github/workflows/differential-shellcheck.yml
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR. The beauty of differential scans is that you will get reports only about newly added defects. 
Since this repository has few shell scripts, I think you might find some value in having a shell linter. Differential ShellCheck action is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to …
> ci(lint): add shell linter - Differential ShellCheck

- Makefile.am
> Set installation root dir from setup.py

- pyproject.toml
None of the listed packages is required to build it.
pip/build invokes this, there is no need to install them into the build environment.
pycups is not used during the build.
> Remove superfulous build requires from pyproject.toml

- newprinter.py
- ui/NewPrinterWindow.ui
In the printer add menu there is no checkbox or any other way to specify whether to use shared access or
not when adding a device. The device is set to the default value defined in CUPS after adding.
The patch adds a new line to the "Describe Printer" section, containing a checkbox that allows users to specify whether to use shared access or not for the device being added
> #375 Add checkbox for sharing when adding a printer
