.travis.yml

then there's no need for requirements.txt

travis.yml: install dependencies in install section

---

newprinter.py

This a refactoring of newprinter.py in an attempt to make the code more readable and, hopefully, more hackable too. The main changes done in this branch are of two types:
* Use constants for page numbers instead of bare numbers
* Refactoring of too big functions into smaller ones. Still not perfect, but a step forward
On top of that, I've also included a small fix for download_gpg_fingerprint() at the beginning of this PR, please let me know if you'd rather have it in a separate branch, or feel free to cherry pick it before the merge.

Code refactoring of newprinter.py

---

authconn.py
cupshelpers/ppds.py
jobviewer.py

Please don't merge yet, let's see what @landscape-bot has to say. :-)

Fixes from landscape.io checking

---

troubleshoot/ErrorLogFetch.py
troubleshoot/PrintTestPage.py

This PR fixes few problems I've spotted when checking how the 'journal' code works.

Troubleshoot

---

Makefile.am
dbus/org.fedoraproject.Config.Printing.service.in

Make D-Bus service file respect configure flags

---

po/ko.po

Correct '취소(D)' to '삭제(D)'

---

po/de.po

This fixes another translation error. This is all I could find.

Removed wrong word "Es" (German/de)

---

xml/preferreddrivers.xml

see https://bugzilla.redhat.com/show_bug.cgi?id=1308688

Fixed preferred driver for CLP-310

---

test/test-cups-driver.py

These cause compile time errors with Python 3.6.1.

Syntax fixes

---

cupshelpers/ppds.py
newprinter.py
options.py

https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

Python 3.6 invalid escape sequence deprecation fixes

---

NEWS
jobviewer.py

use libsecret instead of libgnome-keyring

---

ppdippstr.py

Addition of some strings for i18n

---

ppdippstr.py

I hope now most of the frequent strings will be in the file!

New strings for Hp Canon Samsung Ricoh and Brother

---

po/fr.po
ppdippstr.py

I translated the new strings, and I discovered some errors in the ppdipstr.py. (lack of comma).
If you want I can learn how to run `intltool-update`, in this way, I can contribute when I have time, without boring you :)

Translation of new strings and correction in the ppdipstr.py again

---

system-config-printer.appdata.xml.in

Make the appstream file validate with version >= 0.6

---

ppdippstr.py

I hope this pull request should be useful, when you'll merge it, after the update of the po files, I will translate the new strings.

New strings for the ppd files (ppdippstr.py)

---

cupshelpers/ppds.py

Hi there,
Although the comment has been written like a doc-string but it's not accessible for users.
I've just fixed that part.

convert ppds.normalize comments to doc-string

---

newprinter.py

Use remote server ppd file, in case a printer has been shared via cups

---

jobviewer.py

Fallback to username/password auth in jobviewer

---

po/ko.po

"Delete" means in korean, "삭제".
"Release" means in korean, "재시작".
"Time submitted" means in korean, "입력된 시간"

It is wrong translation. So I modified. \po/ko.po

---

applet.py

Fixes https://github.com/OpenPrinting/system-config-printer/issues/175#issuecomment-977968336

Make sure that applet.py is running one instance per user

---

system-config-printer.py

See https://github.com/python/cpython/blob/3.10/Lib/urllib/parse.py#L1026

Migrate from deprecated splittype to urlparse
